# -*- coding: utf-8 -*-
"""Resutls_graph_XAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1kLXASlPIv8yRfp-5gtmoQIbg5Ee2Ut
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# FEATURE agreemetn
df = pd.read_csv("xai_results_avg.csv")
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_topk_BD_Shap",order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Feature Agreement (BreakDown vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

# RANK agreement
df = pd.read_csv("xai_results_avg.csv")

# GRAPH 2 — Rank Agreement
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_rank_BD_Shap",order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Rank Agreement (BreakDown vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

# SIGN agreement
df = pd.read_csv("xai_results_avg.csv")
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_sign_BD_Shap",order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Sign Agreement (BreakDown vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# load the data
df = pd.read_csv("xai_results_avg.csv")

# GRAPH 4 — Rank+Sign Agreement
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_rank_sign_BD_Shap",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Rank+Sign Agreement (BreakDown vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

df = pd.read_csv("xai_results_avg.csv")

plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_topk_BD_Lime",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Feature Agreement (BreakDown vs LIME)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

df = pd.read_csv("xai_results_avg.csv")

plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_rank_BD_Lime",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Rank Agreement (BreakDown vs LIME)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

df = pd.read_csv("xai_results_avg.csv")

plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_sign_BD_Lime",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Sign Agreement (BreakDown vs LIME)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

df = pd.read_csv("xai_results_avg.csv")

# Feature Agreement
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_topk_Lime_Shap",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Feature Agreement (LIME vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

# Rank Agreement
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_rank_Lime_Shap",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Rank Agreement (LIME vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

df = pd.read_csv("xai_results_avg.csv")

# Sign Agreement (LIME vs SHAP)
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="method", y="Mean_sign_Lime_Shap",
            order=["AP", "GWO", "PSO", "WOA", "EvoCluster_PSO"])
plt.title("Sign Agreement (LIME vs SHAP)")
plt.ylabel("Agreement Score")
plt.xlabel("Clustering Method")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

"""P vs Metaheuristics"""

df = pd.read_csv("xai_results_avg.csv")

# group AP separately from all metaheuristics
df["group"] = df["method"].apply(lambda x: "AP" if x == "AP" else "Metaheuristic")

plt.figure(figsize=(7, 5))
sns.boxplot(data=df, x="group", y="Mean_topk_BD_Shap",
            order=["AP", "Metaheuristic"])
plt.title("Feature Agreement (BreakDown vs SHAP)\nAP vs Metaheuristics")
plt.ylabel("Agreement Score")
plt.xlabel("")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("xai_results_avg.csv")

# group AP separately from metaheuristics
df["group"] = df["method"].apply(lambda x: "AP" if x == "AP" else "Metaheuristic")

# reshape: put all 3 pairs into one long column
df_long = df.melt(
    id_vars=["dataset", "classifier", "method", "group"],
    value_vars=["Mean_topk_BD_Shap", "Mean_topk_BD_Lime", "Mean_topk_Lime_Shap"],
    var_name="pair",
    value_name="score"
)

# rename pairs for nicer labels
pair_names = {
    "Mean_topk_BD_Shap":   "BreakDown vs SHAP",
    "Mean_topk_BD_Lime":   "BreakDown vs LIME",
    "Mean_topk_Lime_Shap": "LIME vs SHAP",
}
df_long["pair"] = df_long["pair"].map(pair_names)

plt.figure(figsize=(10, 6))
sns.boxplot(data=df_long, x="pair", y="score", hue="group")
plt.title("Feature Agreement — AP vs Metaheuristics\nAcross all 3 method pairs")
plt.ylabel("Agreement Score")
plt.xlabel("")
plt.axhline(y=0.5, color="gray", linestyle="--")
plt.legend(title="")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("xai_results_avg.csv")

# group AP separately from metaheuristics
df["group"] = df["method"].apply(lambda x: "AP" if x == "AP" else "Metaheuristic")

# the 4 metrics, each with its 3 pairs
metrics = {
    "Feature":   ["Mean_topk_BD_Shap",      "Mean_topk_BD_Lime",      "Mean_topk_Lime_Shap"],
    "Rank":      ["Mean_rank_BD_Shap",      "Mean_rank_BD_Lime",      "Mean_rank_Lime_Shap"],
    "Sign":      ["Mean_sign_BD_Shap",      "Mean_sign_BD_Lime",      "Mean_sign_Lime_Shap"],
    "Rank+Sign": ["Mean_rank_sign_BD_Shap", "Mean_rank_sign_BD_Lime", "Mean_rank_sign_Lime_Shap"],
}

pair_names = {
    "Mean_topk_BD_Shap": "BD-SHAP",        "Mean_rank_BD_Shap": "BD-SHAP",
    "Mean_sign_BD_Shap": "BD-SHAP",        "Mean_rank_sign_BD_Shap": "BD-SHAP",
    "Mean_topk_BD_Lime": "BD-LIME",        "Mean_rank_BD_Lime": "BD-LIME",
    "Mean_sign_BD_Lime": "BD-LIME",        "Mean_rank_sign_BD_Lime": "BD-LIME",
    "Mean_topk_Lime_Shap": "LIME-SHAP",    "Mean_rank_Lime_Shap": "LIME-SHAP",
    "Mean_sign_Lime_Shap": "LIME-SHAP",    "Mean_rank_sign_Lime_Shap": "LIME-SHAP",
}

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for ax, (metric_name, cols) in zip(axes, metrics.items()):

    df_long = df.melt(
        id_vars=["dataset", "classifier", "method", "group"],
        value_vars=cols,
        var_name="pair_col",
        value_name="score"
    )
    df_long["pair"] = df_long["pair_col"].map(pair_names)

    sns.boxplot(data=df_long, x="pair", y="score", hue="group", ax=ax)
    ax.set_title(metric_name, fontsize=12, fontweight="bold")
    ax.set_ylabel("Agreement Score")
    ax.set_xlabel("")
    ax.axhline(y=0.5, color="gray", linestyle="--")
    ax.legend(title="", fontsize=9)

plt.suptitle("AP vs Metaheuristics — All 4 metrics × 3 method pairs", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("xai_results_avg.csv")

metrics = {
    "Feature":   "Mean_topk_BD_Shap",
    "Rank":      "Mean_rank_BD_Shap",
    "Sign":      "Mean_sign_BD_Shap",
    "Rank+Sign": "Mean_rank_sign_BD_Shap",
}

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
axes = axes.flatten()

for ax, (metric_name, col) in zip(axes, metrics.items()):

    sns.boxplot(data=df, x="dataset", y=col, ax=ax)
    ax.set_title(metric_name, fontsize=12, fontweight="bold")
    ax.set_ylabel("Agreement Score")
    ax.set_xlabel("")
    ax.set_ylim(-0.05, 1.1)
    ax.axhline(y=0.5, color="gray", linestyle="--")
    ax.tick_params(axis='x', rotation=30)
    for label in ax.get_xticklabels():
        label.set_ha('right')

plt.suptitle("XAI Agreement (BreakDown vs SHAP) — Per Dataset", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("xai_results_avg.csv")

# === BreakDown vs LIME ===
metrics_bd_lime = {
    "Feature":   "Mean_topk_BD_Lime",
    "Rank":      "Mean_rank_BD_Lime",
    "Sign":      "Mean_sign_BD_Lime",
    "Rank+Sign": "Mean_rank_sign_BD_Lime",
}

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
axes = axes.flatten()

for ax, (metric_name, col) in zip(axes, metrics_bd_lime.items()):
    sns.boxplot(data=df, x="dataset", y=col, ax=ax)
    ax.set_title(metric_name, fontsize=12, fontweight="bold")
    ax.set_ylabel("Agreement Score")
    ax.set_xlabel("")
    ax.set_ylim(-0.05, 1.1)
    ax.axhline(y=0.5, color="gray", linestyle="--")
    ax.tick_params(axis='x', rotation=30)
    for label in ax.get_xticklabels():
        label.set_ha('right')

plt.suptitle("XAI Agreement (BreakDown vs LIME) — Per Dataset", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

# === LIME vs SHAP ===
metrics_lime_shap = {
    "Feature":   "Mean_topk_Lime_Shap",
    "Rank":      "Mean_rank_Lime_Shap",
    "Sign":      "Mean_sign_Lime_Shap",
    "Rank+Sign": "Mean_rank_sign_Lime_Shap",
}

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
axes = axes.flatten()

for ax, (metric_name, col) in zip(axes, metrics_lime_shap.items()):
    sns.boxplot(data=df, x="dataset", y=col, ax=ax)
    ax.set_title(metric_name, fontsize=12, fontweight="bold")
    ax.set_ylabel("Agreement Score")
    ax.set_xlabel("")
    ax.set_ylim(-0.05, 1.1)
    ax.axhline(y=0.5, color="gray", linestyle="--")
    ax.tick_params(axis='x', rotation=30)
    for label in ax.get_xticklabels():
        label.set_ha('right')

plt.suptitle("XAI Agreement (LIME vs SHAP) — Per Dataset", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()